BEGIN TRANSACTION;
DROP TABLE IF EXISTS `Sections`;
CREATE TABLE IF NOT EXISTS `Sections` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Header`	TEXT NOT NULL,
	`Login`	INTEGER,
	FOREIGN KEY(`Login`) REFERENCES `Logins`(`Id`) ON DELETE CASCADE
);
DROP TABLE IF EXISTS `Section2Profiles`;
CREATE TABLE IF NOT EXISTS `Section2Profiles` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Section`	INTEGER NOT NULL,
	`Profile`	INTEGER NOT NULL,
	FOREIGN KEY(`Profile`) REFERENCES `Profiles`(`Id`) ON DELETE CASCADE,
	FOREIGN KEY(`Section`) REFERENCES `Sections`(`Id`) ON DELETE CASCADE
);
DROP TABLE IF EXISTS `RateLimits`;
CREATE TABLE IF NOT EXISTS `RateLimits` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Timestamp`	INTEGER NOT NULL,
	`Profile`	INTEGER,
	`Duration`	INTEGER NOT NULL DEFAULT 3600
);
DROP TABLE IF EXISTS `Profiles`;
CREATE TABLE IF NOT EXISTS `Profiles` (
	`Id`	INTEGER NOT NULL,
	`Name`	TEXT NOT NULL,
	`Crashed`	INTEGER NOT NULL DEFAULT 0,
	`CursorLocation`	INTEGER NOT NULL DEFAULT 0,
	`Complete`	INTEGER NOT NULL DEFAULT 0,
	`Location`	TEXT,
	`Invalid`	INTEGER NOT NULL DEFAULT 0,
	`LastAttempted`	INTEGER NOT NULL DEFAULT 0,
	CONSTRAINT `nameIsUnique` UNIQUE(`Name`),
	PRIMARY KEY(`Id`)
);
DROP TABLE IF EXISTS `Logins`;
CREATE TABLE IF NOT EXISTS `Logins` (
	`Id`	INTEGER NOT NULL,
	`Username`	TEXT NOT NULL,
	`Password`	TEXT NOT NULL,
	CONSTRAINT `usernameIsUnique` UNIQUE(`Username`),
	PRIMARY KEY(`Id`)
);
COMMIT;
